### ISSUE TITLE
Clarify that a "classic" token is needed for github

### ISSUE THREAD

**Issue by wgustafson** [ARM-Development/arm-summer-school-2024#42]
The token generation instructions, as written now, assume creation of a classic token. Make this clear so students do not get confused by trying to create a find-grained token, which is the newer best practice suggested by Github.

Classic tokens are created in https://github.com/settings/tokens. Whereas, the fine-grain tokens are generated at https://github.com/settings/tokens?type=beta. 

The page in the summer school repository to modify is <https://arm-development.github.io/arm-summer-school-2024/preliminary/checklist/git.html>.

**Comment by jrobrien91** [comment]
A side note @mgrover1 this directory name needs to be updated here from `github_setup_check` to `check_github_setup`:
```
# Go inside the directory
(notebook) jovyan@jupyter:~$ cd github_setup_check/
# Issue the pull command
(notebook) jovyan@jupyter:~/github_setup_check$ git pull
Already up to date.
```
and 
```
rm -rf github_setup_check
```

within the `~/preliminary/checklist/git.md` file

**Comment by mgrover1** [comment]
thanks @jrobrien91 👍
